In [266]:
import pandas as pd

data = pd.DataFrame({
    'name' : ['Adi','Khushi',"Riddhi"] , 
    'srno' : [1,2,3] ,
    'marks':[20,25,32],
})
print(data) 
print("____________________________________________")
s = pd.DataFrame({
    'name' : ["Adit" , "Khushi" , "Riddhi"],
    'maths' :[23 , 21,22] ,
    'english' : [23,33,44]
})
dict1 = {'name': ['Aditya',212] , 'srno':'0018'}
print(pd.Series(dict1))

     name  srno  marks
0     Adi     1     20
1  Khushi     2     25
2  Riddhi     3     32
____________________________________________
name    [Aditya, 212]
srno             0018
dtype: object

In [267]:
s = pd.Series([1,2,3,4,5,6,7],index = ['a','b','c','d','e','f','g'])
print( s['f'])
print("_________________________________________________________________")
s2 = pd.Series([1,2,3,4,5,6,7])
s2 *=10 
print(s2.mean())

6
_________________________________________________________________
40.0

In [268]:
import pandas as pd
import numpy as np
s2 = pd.Series([1,2,3,4,5,6,7])
s2*=10 
print(s2.mean()+2)
s1 = np.log(s2)
print(s1)

42.0
0    2.302585
1    2.995732
2    3.401197
3    3.688879
4    3.912023
5    4.094345
6    4.248495
dtype: float64

In [269]:
data_set = pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv")

In [270]:
print(data_set)

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [271]:
print(data_set[(data_set['sepal_length']>=5.7) | (data_set['species'] == 'setosa')])

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[132 rows x 5 columns]

In [272]:
data_set['sepal_ratio'] = data_set['sepal_length'] / data_set['sepal_width']
print(data_set['petal_width'].iloc(0))

<pandas.core.indexing._iLocIndexer object at 0x736baebfd900>

In [273]:
print(data_set.isnull().sum())

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
sepal_ratio     0
dtype: int64

In [274]:
print(data_set.groupby('species').mean())

            sepal_length  sepal_width  petal_length  petal_width  sepal_ratio
species
setosa             5.006        3.428         1.462        0.246     1.470188
versicolor         5.936        2.770         4.260        1.326     2.160402
virginica          6.588        2.974         5.552        2.026     2.230453

In [275]:
data_set.groupby('species')['sepal_length'].agg(['mean','min','max','sum'],)

             mean  min  max    sum
species
setosa      5.006  4.3  5.8  250.3
versicolor  5.936  4.9  7.0  296.8
virginica   6.588  4.9  7.9  329.4

In [276]:
data_set.sort_values(by='sepal_length',ascending=False)

,sepal_length,sepal_width,petal_length,petal_width,species,sepal_ratio
131,7.9,3.8,6.4,2.0,virginica,2.078947
122,7.7,2.8,6.7,2.0,virginica,2.750000
118,7.7,2.6,6.9,2.3,virginica,2.961538
117,7.7,3.8,6.7,2.2,virginica,2.026316
135,7.7,3.0,6.1,2.3,virginica,2.566667
...,...,...,...,...,...,...
41,4.5,2.3,1.3,0.3,setosa,1.956522
42,4.4,3.2,1.3,0.2,setosa,1.375000
8,4.4,2.9,1.4,0.2,setosa,1.517241
38,4.4,3.0,1.3,0.2,setosa,1.466667
13,4.3,3.0,1.1,0.1,setosa,1.433333

In [277]:
df1 = pd.DataFrame(
    {
        'id' : [2,4,5],
        'name' : ['Adi',"khushi",'anushka'],
        
    }
)
df2 = pd.DataFrame ({
    'id' :[1,2,3] , 
    'score' : [21,32,43] 
})
df3 = pd.merge(df1,df2 )
print(df3)

   id name  score
0   2  Adi     32

Titanic DataSet

In [278]:
csv = 'https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv'
titanic = pd.read_csv(csv)

In [279]:
print(titanic)

     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500   NaN        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[891 rows x 12 columns]

In [280]:
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [281]:
titanic.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [282]:
titanic.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [283]:
titanic.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

fill the missing values of age with mean age

In [284]:
titanic['Age']

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [285]:
# titanic["Age"]= titanic['Age'].fillna(titanic['Age'].mean(),inplace=True)

In [286]:
titanic.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [287]:
titanic['Cabin'] = titanic['Cabin'].fillna("Not Found")

In [288]:
titanic['Cabin'].info()

<class 'pandas.Series'>
RangeIndex: 891 entries, 0 to 890
Series name: Cabin
Non-Null Count  Dtype
--------------  -----
891 non-null    str
dtypes: str(1)
memory usage: 7.1 KB

droping the Cabin Value

In [289]:
titanic.drop('Cabin',axis=1,inplace=True)

In [290]:
titanic.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(4)
memory usage: 76.7 KB

Analyze Survival patterns

In [291]:
# survival Rate
survival_rate = int(titanic["Survived"].mean() *100)
print(survival_rate)

38

In [292]:
titanic.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(4)
memory usage: 76.7 KB

In [293]:
survival_rate_male = titanic[titanic['Sex'] == 'male']['Survived'].mean()*100
print(survival_rate_male)
survival_rate_female = titanic[titanic['Sex']=='female']["Survived"].mean()*100
print(survival_rate_female)
print(survival_rate_female+survival_rate_male)

18.890814558058924
74.20382165605095
93.09463621410987

In [294]:
titanic.groupby("Sex")['Survived'].mean()*100

Sex
female    74.203822
male      18.890815
Name: Survived, dtype: float64

In [295]:
titanic.groupby("Pclass")['Survived'].mean()*100

Pclass
1    62.962963
2    47.282609
3    24.236253
Name: Survived, dtype: float64

In [296]:
titanic.groupby('Survived')['Age'].mean()

Survived
0    30.626179
1    28.343690
Name: Age, dtype: float64

finding the servival rate of children age < 16

In [297]:
print(titanic[titanic["Age"]<16]["Survived"].mean()*100)

59.036144578313255

In [309]:
titanic[titanic['Survived']==1 & titanic['Age'].isna()].sort_values(by='Age',ascending=True).min()

PassengerId                      1
Survived                         0
Pclass                           1
Name           Abbing, Mr. Anthony
Sex                         female
Age                            1.0
SibSp                            0
Parch                            0
Ticket                      110413
Fare                           0.0
Embarked                         C
dtype: object

16 < Age < 60

In [312]:
titanic[(titanic['Age']>16) &( titanic['Age']<60)].sort_values(by='Age',ascending=True)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
68,69,1,3,"Andersson, Miss. Erna Alexandra",female,17.0,4,2,3101281,7.9250,S
844,845,0,3,"Culumovic, Mr. Jeso",male,17.0,0,0,315090,8.6625,S
84,85,1,2,"Ilett, Miss. Bertha",female,17.0,0,0,SO/C 14885,10.5000,S
781,782,1,1,"Dick, Mrs. Albert Adrian (Vera Gillespie)",female,17.0,1,0,17474,57.0000,S
114,115,0,3,"Attalah, Miss. Malake",female,17.0,0,0,2627,14.4583,C
...,...,...,...,...,...,...,...,...,...,...,...
659,660,0,1,"Newell, Mr. Arthur Webster",male,58.0,0,2,35273,113.2750,C
268,269,1,1,"Graham, Mrs. William Thompson (Edith Junkins)",female,58.0,0,1,PC 17582,153.4625,S
487,488,0,1,"Kent, Mr. Edward Austin",male,58.0,0,0,11771,29.7000,C
94,95,0,3,"Coxon, Mr. Daniel",male,59.0,0,0,364500,7.2500,S
232,233,0,2,"Sjostedt, Mr. Ernst Adolf",male,59.0,0,0,237442,13.5000,S

Creating an Age group based on the child Adult and Senior

In [314]:
bins = [0,16,60 ,float('inf')]
labels = ['child',"Adult",'senior']
titanic['AgeGroup'] = pd.cut(titanic['Age'],bins=bins,labels=labels,right=False)
titanic.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,AgeGroup
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,S,Adult
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,S,Adult
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,S,NaN
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C,Adult
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,Q,Adult

In [317]:
titanic[titanic['AgeGroup']=='child']

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,AgeGroup
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.00,3,1,349909,21.0750,S,child
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.00,1,0,237736,30.0708,C,child
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.00,1,1,PP 9549,16.7000,S,child
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.00,0,0,350406,7.8542,S,child
16,17,0,3,"Rice, Master. Eugene",male,2.00,4,1,382652,29.1250,Q,child
...,...,...,...,...,...,...,...,...,...,...,...,...
831,832,1,2,"Richards, Master. George Sibley",male,0.83,1,1,29106,18.7500,S,child
850,851,0,3,"Andersson, Master. Sigvard Harald Elias",male,4.00,4,2,347082,31.2750,S,child
852,853,0,3,"Boulos, Miss. Nourelain",female,9.00,1,1,2678,15.2458,C,child
869,870,1,3,"Johnson, Master. Harold Theodor",male,4.00,1,1,347742,11.1333,S,child
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.00,0,0,2667,7.2250,C,child

In [320]:
titanic.groupby('AgeGroup')['Survived'].mean()*100

AgeGroup
child     59.036145
Adult     38.677686
senior    26.923077
Name: Survived, dtype: float64